project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
    - "!fragments/"
    - "!1-getting-started/"
    - "!2-data-wrangling/"
    - "!3-quarto-plotting/"
    - "!4-workshop-proposals/"
    - "!5-intro-to-surveydown/"
    - "!6-conjoint-questions/"
    - "!7-utility-models/"
    - "!8-optimization-mle/"
    - "!9-uncertainty/"
    - "!10-doe-power-analysis/"
    - "!11-wtp-simulation/"
    - "!12-heterogeneity/"
    - "!13-class-review/"
    - "!14-story-telling/"
    - "!15-final-presentations/"
  resources:
    - "class/"
    - "rubrics/"
    - "data/"
    - "content/"
    - "project/"
    - "templates/"

website:
  title: EMSE 6035
  image: images/logo.png
  site-url: https://madd.seas.gwu.edu/2025-Fall/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-madd-gwu/2025-Fall
  repo-actions: [edit, issue]
  description: 'Course website for Fall 2025 semester of the EMSE course "Marketing Analytics for Design Decisions" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://madd.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo-square.png"
    card-style: summary
  sidebar:
    style: "docked"
    background: "dark"
    collapse-level: 1
    search: true
    contents:
      - text: Home
        icon: house-door-fill
        href: index.qmd
      - text: Syllabus
        icon: map-fill
        href: syllabus.qmd
      - text: Schedule
        icon: table
        href: schedule.qmd
      - section: Final Project
        icon: pencil-square
        contents:
          - text: Overview
            href: project/0-overview.qmd
          - text: Proposal
            href: project/1-proposal.qmd
          - text: Survey Plan
            href: project/2-survey-plan.qmd
          - text: Pilot Survey
            href: project/3-pilot-survey.qmd
          - text: Pilot Analysis
            href: project/4-pilot-analysis.qmd
          - text: Final Survey
            href: project/5-final-survey.qmd
          - text: Final Analysis
            href: project/6-final-analysis.qmd
          - text: Final Presentation
            href: project/7-final-presentation.qmd
          - text: Examples
            icon: file-earmark-medical
            href: project/examples.qmd
      - text: Software
        icon: download
        href: software.qmd
      - text: FAQ
        icon: question-square-fill
        href: faq.qmd
      - text: References
        icon: bookmark-fill
        href: references.qmd
      - text: Project Showcase
        icon: bar-chart-line-fill
        href: https://madd.seas.gwu.edu/showcase.html#fall-2025
      - text: Slack
        icon: slack
        href: https://emse-madd-f25.slack.com
      - text: "Schedule a call w/Prof. Helveston"
        icon: clock-fill
        href: https://jhelvy.appointlet.com/b/professor-helveston
      - section: Other
        icon: question-circle-fill
        contents:
          - text: About
            icon: question-circle-fill
            href: about.qmd
          - text: License
            icon: award-fill
            href: LICENSE.qmd
          - text: Contact
            icon: envelope-fill
            href: mailto:jph@gwu.edu
          - text: Source files
            icon: github
            href: https://github.com/emse-madd-gwu/2025-Fall
  page-footer:
    center:
      - text: "© 2025 John Paul Helveston {{< fa creative-commons-sa >}} <a href='LICENSE.html'><i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a><br><i class='far fa-calendar-alt'></i> {{< var weekday >}} | <i class='far fa-clock'></i> {{< var time >}} | <a href='{{< var room_url >}}'><i class='fa fa-map-marker-alt'></i> {{< var room >}}</a><br><a href='https://www.jhelvy.com'><i class='fas fa-user'></i> Dr. John Paul Helveston</a> | <a href='mailto:{{< var email >}}'><i class='fas fa-envelope'></i> {{< var email >}}</a> | <a href='{{< var repo >}}'><i class='fab fa-github'></i></a>"

format:
  html:
    theme: united
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    # This is to include fontawesome icons
    include-in-header: "_includes/header.html"

filters:
    - schedule.lua
