---
title: "Design of Experiment"
params:
  number: 8
  purpose: "The purpose of this assignment is to introduce the concept of design of experiments and to understand how experiment design can impact the amount of information available about different model effects."
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

# 2. Readings

Last week we discussed how we quantify parameter uncertainty from maximizing the log-likelihood. This week, we'll begin considering the relationship between parameter uncertainty and how we design our experiment.

**Take notes** as you watch the video. At the end of the video, I ask one practice question - you should answer this questions as part of your reflection. You may submit your answers however you wish, e.g. hand-write them on paper and take a picture and / or type answers in your reflection .Rmd file.

Click [here](../content/slides_doe.pdf) to download the slides in the video as a PDF.

<center>
<iframe width="640" height="360" src="https://www.youtube.com/embed/xmlGINu0_k8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>

# 3. Reflect

Reflect on what you've learned while going through these readings and exercises. Is there anything that jumped out at you? Anything you found particularly interesting or confusing? Write at least a paragraph in your ``r hw_file`` file, and include at least one question. The teaching team will review the questions we get and will try to answer them either in Slack or in class.

If you're unsure where to start with a reflection, try filling out this template:

> "I used to think ______, now I think ______ 🤔"

# 4. Submit

To submit your assignment, follow these instructions:

1. Render your .qmd file by either clicking the "Render" button in RStudio or running the command ``r paste0('quarto::quarto_render("', hw_file, '")')`` command.
2. Open the rendered html file and make sure it looks good! Is all the formatting as you expected?
3. Create a zip file of all the files in your R project folder for this assignment and submit it on the corresponding assignment submission on Blackboard.
